### ISSUE TITLE
Power/Torque Coefficients

### ISSUE THREAD

**Issue by JoeSpencer1** [JoeSpencer1/497R-Projects#6]
What's the relation between CP and CQ?

**Comment by Cardoza2** [comment]
Cp and Cq are related by a simple factor of 2*pi. If this were real, I would write out the whole discussion that we had on the whiteboard. ...

**Comment by JoeSpencer1** [comment]
Thank you so much.

**Comment by JoeSpencer1** [comment]
Waiting to close until code is fixed

**Comment by JoeSpencer1** [comment]
Added explanation of relationship between power and torque coefficients.
